apiVersion: v1
kind: Service
metadata:
  name: pgstorage
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: pgstorage
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pgstorage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pgstorage
    spec:
      containers:
        - name: pgstorage
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: pact
            - name: POSTGRES_PASSWORD
              value: pact
            - name: POSTGRES_DB
              value: pact
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}