apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  ports:
  - name: recommendation
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: recommendation
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: recommendation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: samplejapan.azurecr.io/consumer:latest
          env:
            - name: PROVIDER_HOST
              value: product
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: simplejapankey
